source :gemcutter

gem "rails", "3.0.11"

gem "cancan", "1.3.4"
gem "clearance", "0.9.1"
gem "carrierwave"
gem "compass", "0.11.5"
gem "escape_utils"
gem "exceptional"
gem "formtastic", "2.0.2"
gem "friendly_id"
gem "geokit"
gem "gravtastic", "2.2.0"
gem "haml"
gem "httparty", "0.6.1"
gem "home_run", :require => "date"
gem "jammit", "0.6.5"
gem "newrelic_rpm"
gem "mini_magick"
gem "resque", :require => "resque/server"
gem "resque_mailer"
gem "roadie", "1.0.0.pre2"
gem "padlock", "0.1.0"
gem "paperclip", "2.3.5"
gem "pg", "0.12.0"
gem "rdiscount", "1.6.8"
gem "retryable"
gem "sass"
gem "sunspot_rails"
gem "sunspot_solr"
gem "state_machine", "0.9.4"
gem "steak", "2.0.0"
gem "timeline_fu", "0.3.0"
gem "twitter_oauth", "0.4.0"
gem "unicorn"
gem "whenever"
gem "will_paginate", "3.0.2"
gem "xml-sitemap", "1.2.2"

group :test do
  gem "capybara", "1.1.2"
  gem "database_cleaner", "0.5.2"
  gem "factory_girl_rails"
  gem "ffaker"
  gem "fixture_builder"
  gem "remarkable_activerecord", "4.0.0.alpha4"
  gem "resque_spec"
  gem "rspec-rails"
  gem "webmock", "1.3.5"
end

group :development do
  gem "capistrano"
  gem "capistrano-ext"
  gem "capistrano-unicorn"
  gem "mailcatcher"
  gem "passenger"
  gem "pony"
  gem "progress_bar"
  gem "rspec-rails"
end
