development:
  adapter: postgresql
  encoding: unicode
  database: cozily_development
  pool: 5
  host: localhost
  username: cozily
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: cozily_test
  pool: 5
  host: localhost
  username: cozily
  password:
